alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
databases:
  - cluster_name: elevator-system-db
    engine: MONGODB
    name: elevator-system-db
    production: true
    version: "7"
features:
  - buildpack-stack=ubuntu-22
ingress:
  rules:
    - component:
        name: elevator-system-api
      match:
        path:
          prefix: /api
name: dolphin-app
region: fra
services:
  - dockerfile_path: /api/Dockerfile
    envs:
      - key: DATABASE_URL
        scope: RUN_TIME
        value: ${elevator-system-db.DATABASE_URL}
      - key: CA_CERT
        scope: RUN_TIME
        value: ${elevator-system-db.CA_CERT}
    github:
      branch: main
      deploy_on_push: true
      repo: mikolajkapica/elevator-system
    http_port: 8080
    instance_count: 2
    instance_size_slug: apps-s-1vcpu-1gb
    name: elevator-system-api
    source_dir: api
