alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
features:
  - buildpack-stack=ubuntu-22
ingress:
  rules:
    - component:
        name: elevator-system-api
      match:
        path:
          prefix: /api
jobs:
  - dockerfile_path: api/Dockerfile
    github:
      branch: feature/4
      repo: mikolajkapica/elevator-system
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-0.5gb
    source_dir: api
name: elevator-system
region: fra
services:
  - dockerfile_path: api/Dockerfile
    github:
      branch: feature/4
      repo: mikolajkapica/elevator-system
    http_port: 8080
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-0.5gb
    name: elevator-system-api
    run_command: sbt run
    source_dir: api