name: elevator-system

services:
    api:
        build:
            context: .
        ports:
            - 8080:8080
        environment:
            - DATABASE_URL=mongodb://db:27017
    db:
        image: mongo:7
        ports:
            - 27017:27017
